
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/app/configs:ro
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:secret@postgres:5432/postgres?sslmode=require
      - DATABASE_PASSWORD = DB_password

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./certs/server.crt:/var/lib/postgresql/server.crt
      - ./certs/server.key:/var/lib/postgresql/server.key
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "ssl=on"
      - "-c"
      - "ssl_cert_file=/var/lib/postgresql/server.crt"
      - "-c"
      - "ssl_key_file=/var/lib/postgresql/server.key"
volumes:
  postgres_data:




