#version: '3.9'

services:
  backend:
    build: .
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/app/configs:ro
    depends_on:
      - postgres
      - ollama
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - LLM_URL=http://ollama:11434
    networks:
      - todo-net

  postgres:
    image: postgres:latest
    container_name: todo-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=postgres
    networks:
      - todo-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - todo-net
    dns:
      - 8.8.8.8
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0:11434


volumes:
  postgres_data:
  ollama-data:

networks:
  todo-net:
    driver: bridge