services:

  backend:
    build: .
    ports: ["8000:8000"]
    volumes:
      - ./configs:/app/configs:ro
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=postgres
volumes:
  postgres_data:




